### ISSUE TITLE
Because flutter_html_view >=0.4.0 depends on flutter_custom_tabs

### ISSUE THREAD

**Issue by thenexus00** [PonnamKarthik/FlutterHtmlView#38]
The title error is occurring on builds after flutter on the dev channel was upgraded to 0.6.0
Flutter 0.6.0 
Dart 2.1.0-dev.0.0

**Comment by l-k22** [comment]
Experiencing similar problem, flutter_html_view 0.5.4 depends on flutter_custom_tabs ^0.1.0
Dart 2.1.0-dev.1.0

**Comment by daniel-van-niekerk** [comment]
+1

**Comment by AbdulRahmanAlHamali** [comment]
+1

This is a blocking issue, I hope you guys can fix it asap

**Comment by NTFLeo** [comment]
+1

**Comment by HannoOttens** [comment]
+1

**Comment by koraxis** [comment]
+1

**Comment by audreybartlett** [comment]
+1

**Comment by ponnamkarthik** [comment]
updated in latest version v0.5.5

**Comment by HannoOttens** [comment]
Now I get another error (on v0.7.3):

'Because flutter_html_view >=0.5.5 depends on cached_network_image ^0.4.1 which depends on flutter_cache_manager ^0.1.1, flutter_html_view >=0.5.5 requires flutter_cache_manager ^0.1.1.
And because no versions of flutter_cache_manager match >0.1.1 <0.2.0 and flutter_cache_manager 0.1.1 depends on uuid ^0.5.3, flutter_html_view >=0.5.5 requires uuid ^0.5.3.
Because uuid 0.5.3 requires SDK version >=1.0.0 <2.0.0 and no versions of uuid match >0.5.3 <0.6.0, uuid ^0.5.3 is forbidden.
Thus, flutter_html_view >=0.5.5 is forbidden.'

You can see this on your [dart package analyis page](https://pub.dartlang.org/packages/flutter_html_view#-analysis-tab-)

**Comment by HannoOttens** [comment]
Same issue on v6.2.0

**Comment by HannoOttens** [comment]
Same issue on v6.0.0 

EDIT:
Just tested it on the actual beta branch aswell, got the same error.

**Comment by ponnamkarthik** [comment]
@HannoOttens  Please check the latest version v0.5.6 [Issue 40](https://github.com/PonnamKarthik/FlutterHtmlView/issues/40) Fixed
