### ISSUE TITLE
 Cannot be imported on flutter 0.7.2 version

### ISSUE THREAD

**Issue by FirePrayer** [PonnamKarthik/FlutterHtmlView#40]
Because flutter_html_view >=0.5.5 depends on cached_network_image ^0.4.1 which depends on flutter_cache_manager ^0.1.1, flutter_html_view >=0.5.5 requires flutter_cache_manager ^0.1.1.
And because flutter_cache_manager >=0.1.0-rc.1 depends on uuid ^0.5.3, flutter_html_view >=0.5.5 requires uuid ^0.5.3.
So, because uuid >=0.0.7 <1.0.3 requires SDK version <2.0.0 and flutter_test03 depends on flutter_html_view ^0.5.5, version solving failed.
pub get failed (1)

**Comment by daniel-van-niekerk** [comment]
Still the same issue for Flutter 0.60.

Because flutter_html_view >=0.5.5 depends on cached_network_image ^0.4.1 which depends on flutter_cache_manager ^0.1.1, flutter_html_view >=0.5.5 requires flutter_cache_manager ^0.1.1.
And because flutter_cache_manager >=0.1.0-rc.1 depends on uuid ^0.5.3, flutter_html_view >=0.5.5 requires uuid ^0.5.3.
So, because uuid >=0.0.7 <1.0.3 requires SDK version <2.0.0 and game_tester_mobile_flutter depends on flutter_html_view ^0.5.5, version solving failed.

**Comment by Gidrek** [comment]
This is my fork

https://github.com/Gidrek/FlutterHtmlView

I just update the `cached_network_image` library, that is another fork because both libraries are not updated to flutter 0.6

We need to wait for an official update, but for now, my fork is working.

**Comment by PonnamKarthik** [comment]
@Gidrek could make a pull request ?

**Comment by ponnamkarthik** [comment]
@Gidrek could make a pull request ?

**Comment by Gidrek** [comment]
Done

**Comment by ponnamkarthik** [comment]
@Gidrek  Thanks Merged check v0.5.6
